apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzurePodEnforceLabels
metadata:
  name: "pod-enforce-labels"
spec:
  match:
    excludedNamespaces: ["kube-system"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    labels: ["app"]
